# Configuration for pre-commit hooks: https://pre-commit.com/

default_language_version:
    python: python3.10

repos:
    - repo: local
      hooks:
          - id: cache-clean
            name: cache-clean (script)
            entry: ./.config/scripts/cache_clean.sh
            language: script
            pass_filenames: false
            args: ["."]

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-merge-conflict
          - id: check-vcs-permalinks
          - id: check-added-large-files
            args: ["--maxkb=1000"]
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-ast
          - id: fix-encoding-pragma
            args: ["--remove"]
          - id: name-tests-test
            args: ["--pytest-test-first"]
          - id: check-toml
          - id: check-yaml
          # - id: detect-aws-credentials
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: trailing-whitespace
            args: ["--markdown-linebreak-ext=md"]
          - id: mixed-line-ending
            args: ["--fix=lf"]

    - repo: https://github.com/python-poetry/poetry
      rev: 1.6.0
      hooks:
          - id: poetry-check
          #   - id: poetry-lock
          #   - id: poetry-export
          #     args:
          #         [
          #             "-f",
          #             "requirements.txt",
          #             "-o",
          #             "requirements.txt",
          #             "--without-hashes",
          #             "--with",
          #             "dev",
          #         ]

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v3.0.3"
      hooks:
          - id: prettier
            # types_or: [json, yaml]
            exclude_types: [markdown, python, toml]
            args:
                [
                    "--config",
                    ".prettierrc",
                    "--write",
                    "--ignore-path",
                    ".prettierignore",
                    "--ignore-unknown",
                ]
            # additional_dependencies: ["prettier", "prettier-plugin-multiline-arrays"]

    - repo: https://github.com/psf/black
      rev: 23.7.0
      hooks:
          - id: black
            args: ["--config", ".config/formatter.toml"]

    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            name: isort (python)
            args: ["--settings-path", ".config/formatter.toml"]

    - repo: https://github.com/pycqa/pydocstyle
      rev: 6.3.0 # pick a git hash / tag to point to
      hooks:
          - id: pydocstyle
            name: pydocstyle (python)
            additional_dependencies: [tomli]
            args: ["--config", ".config/formatter.toml"]
            entry: bash -c 'pydocstyle "$@" || true' --

    - repo: https://github.com/PyCQA/docformatter
      rev: v1.7.5
      hooks:
          - id: docformatter
            additional_dependencies: [tomli]
            args: ["--in-place", "--recursive", "--diff", "."]
